version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - cityvoice_db:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    depends_on:
      - db
    healthcheck:
      # Pings your API. If it gets a 200 OK, it marks the container as healthy.
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "80:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15-alpine # Alpine is a lightweight version, great for dev
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "5432:5432" # This allows you to connect a local tool like DBeaver or pgAdmin
    volumes:
      # This is the magic for persistent storage.
      # It maps the named volume to where Postgres stores its actual data files.
      - cityvoice_db:/app/data

volumes:
  cityvoice_db:
