name: EC2 Native Build

on:
  push:
    branches:
      - main

jobs:
  build-on-ec2:
    # This targets your EC2 instance running the GitHub Actions agent
    runs-on: self-hosted

    steps:
      - name: Clean workspace
        run: sudo rm -rf $GITHUB_WORKSPACE/*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Build Commands
        run: |
          # echo "This is running directly on the EC2 hardware"
          # E.g., docker build, make install, or ollama model pulling
          docker compose up -d --build --remove-orphans

        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
